### ISSUE TITLE
replace set-prompt with starship-based prompt

### ISSUE THREAD

**Issue by dmccaffery** [pulsebridge/uber#76]
[Starship](https://starship.rs) is a fantastic and highly customisable prompt that can (and likely should) replace the script-based prompt we include. Most of the functionality of prompt remains; this would only impact the look and feel.

![image](https://user-images.githubusercontent.com/1803684/102746284-e1880100-4355-11eb-9f72-1e1a07a579a8.png)

**Comment by dmccaffery** [comment]
@sjk07 / @patrickserrano : submitted draft PR #77 that adds this functionality -- if you guys think the above looks good, I'll submit the PR formally.

**Comment by patrickserrano** [comment]
@dmccaffery I was using starship before prompt, so I support this change. That said can you just walk through the components of the first line of the prompt? 

It looks like
```
<cwd> on <branch> <git activity> on <machine> on <other machine?> 
```

Also does this change include displaying the pyenv/direnv in the prompt still or will that need to be added in a separate PR?

**Comment by dmccaffery** [comment]
It does include python env, GoLang, nvm, kubernetes context, etc. The two things on the end in my case are the cloud regions (aws is the orange, gcp is the blue) based on my configuration.

Starship is highly adaptive to context, but the default configuration will be included in the user profile in the PR if you want to take a look. I only change a few things; mainly adding counts to git status as well as using real logos as symbols from fira code nerd font.

**Comment by dmccaffery** [comment]
Here is the config:

https://github.com/automotiveMastermind/prompt/blob/656d329c3c4e90df94444b33439ba2adf389548d/src/user/starship.toml

Note that GitHub doesn't render the utf symbols correctly -- but these are the logos for the various languages / frameworks out of nerd fonts.

**Comment by sjk07** [comment]
I have had some issues with starship in powershell... instantly hangs when I go into a git repo for ages. Ill check to see how it works on wsl2 since we don't support powershell anyway

**Comment by sjk07** [comment]
This might be just a windows thing. current prompt in wsl is slow in git repos as well (not as slow)

**Comment by dmccaffery** [comment]
git is slow in general in WSL  -- starship is faster than the script based prompt on windows / linux, which makes sense as its not forking child processes to parse the porcelain output.
